### ISSUE TITLE
API returning inconsistent JSON

### ISSUE THREAD

**Issue by wokket** [EDSM-NET/FrontEnd#110]
A quick report that presents to me as a bug: The system API returns it's json in a weird manner ....

`https://www.edsm.net/api-v1/system?showId=1&systemName=doesntExist` returns an empty _array_
`https://www.edsm.net/api-v1/system?showId=1&systemName=sol` returns a single _object_

This makes parsing the results more difficult than it should be, because we don't know whether to deserialise to an object or an array

Any chance we could take an update to always return a list of matching systems, which may be an empty set?

**Comment by Quit** [comment]
This also occurs in other parts of the API. `/api-v1/sphere-systems` with `showInformation=1` returns either a filled object, or an empty array.

For my purpose, this means I have to pre-process the response before I can deserialize it, as JSON.NET doesn't like the ambiguity at all.

**Comment by klightspeed** [comment]
This is a side-effect of PHP not having separate array and dictionary objects - it has associative arrays.

[`json_encode`](http://php.net/manual/en/function.json-encode.php) only gives the option to force the top-level entity to be an object.  There is no way to force certain inner properties to be objects other than inserting dummy properties.

**Comment by Quit** [comment]
I'm not familiar at all with PHP's JSON utilities, but what about `JSON_FORCE_OBJECT`? At least according to the [docs](https://secure.php.net/manual/en/json.constants.php), it seems like it could help in these cases.

If that doesn't do the trick, another option could be to either try setting the property to JSON's `null`, or not set it at all. The latter wouldn't be acceptable for root-objects, but in that case a small workaround for empty-or-{}/empty-or-null could work.

**Edit**: It's been a while, but casting the bit explicitly to `object` seems to do the trick: `json_encode((object)array());` returns `{}`; `json_encode(array("information" => (object)array()))` returns `{"information":{}}`. I have absolutely no idea if this is applicable or has some backsides at all, it's been ages since I've dabbled in PHP.

**Comment by klightspeed** [comment]
So in order to fix this, anything that should be serialized as a json object should be explicitly cast to `object`.

Note that changing the empty response from `api-v1/system` from an empty array to e.g. `null` would break some programs that rely on the current behaviour.

**Comment by AnthorNet** [comment]
Yes like said over Discord, it not that we cannot, it's more that we do not want to break any existing software using our API.

@klightspeed @Marginal mainly do you know if that broke something or easily fixable on your side?

**Comment by klightspeed** [comment]
EDDiscovery will currently handle returning 404 not found for a non-existent system.

EDDiscovery/EDDiscovery#1718 updates this to handle anything that isn't an object with a `name` field.

It doesn't look like EDMC uses any api-v1 endpoints, and EDDI apparently only uses the `submit-distances` endpoint.

**Comment by AnthorNet** [comment]
This is fixed on all api-system-v1 endpoints, sphere/cube.

The system endpoint will have to wait for EDD release.
