### ISSUE TITLE
'Pending Outages' Warnings

### ISSUE THREAD

**Issue by DaddaTheButt** [EDSM-NET/FrontEnd#133]
Whilst I wait for the current upgrade to complete ...

I did happen to see on the forums yesterday that there was a 'planned outage' for today and thought 'what if I hadn't seen that and had a mega-session planned?'.

What I do always see is EDSM homepage as I login - with a (usually) big Green 'Servers OK'.

If an outage is known could that be 'Amber' with a 'Pending Outages' message - then, anyone who knows of an outage but seeing that EDSM isn't warning of it, can inform EDSM to change it and thereby warn everyone else?

Doubly nice if warning somehow get's passed through to EDDiscovery/MarketConnector.

**Comment by AnthorNet** [comment]
The status only return the current status of the server, and right now:
![image](https://user-images.githubusercontent.com/654353/36731342-c0f6c5e4-1bca-11e8-90da-78e8e2aec608.png)

I do not intend to prepare messages before game update! Specially since an email was sent to every game user that the new version was coming today.

**Comment by DaddaTheButt** [comment]
That's OK - as implied, I hadn't seen any email (nor can I find one - Steam purchase (as opposed to direct) issue possibly) and thought others may be in same position re any future planned outages.
