### ISSUE TITLE
API and nightly dumps don't have body orbital heirarchies

### ISSUE THREAD

**Issue by NecroBones** [EDSM-NET/FrontEnd#157]
I noticed that within the EDSM website UI, the planets have a hierarchy with indentation under their parent bodies, but the JSON outputs from both the API and nightly dumps don't seem to have a parent body ID or any other way to derive this hierarchy. Would it be possible to add parent body ID to each body in the JSON dumps? Is this actually tracked and stored this way?

**Comment by AnthorNet** [comment]
What we use and should be in the API, dumps use the same method to generate the line, is the offset, they should be sorted also

**Comment by NecroBones** [comment]
OK I'll have to take a closer look at the API. I've been using mostly the dumps, since I'm trying to generate some statistics and graphs from the whole galaxy. I was going to look at habitable zone data, in terms of where terraforming candidates are actually found, but the dumps don't seem to have a way to associate the planets with their stars, unless I want to start parsing it out of the names.

**Comment by klightspeed** [comment]
I think the indentation level is the `offset` property on the body.

For most bodies, you can use the body's designation to determine its hierarchical position within the system.

For bodies scanned since 3.0, you can use the `parents` property, which is a list of parent `type: bodyId` tuples starting at the parent body and ending at the root node.

For name-overridden bodies, I have been keeping a mapping of body names to designations at https://docs.google.com/spreadsheets/d/1kDtQYMeduzWghj1yXEsMY8isRccNhAr2XxYmaPIsB2o/edit#gid=711269421

**Comment by NecroBones** [comment]
How many bodies/systems can be pulled at once, in each API call? Like I said, I want to do some galaxy-wide analysis, so if I need to hit the API for some details that aren't in the nightly dumps, I'll have to write a script that queries everything sequentially and slowly fills in the pieces that are missing from the data-set that I'm maintaining. Not ideal, but doable.

**Comment by AnthorNet** [comment]
1 system/call.

What would you not have in the dumps? As said method to generate the line is the same for dumps and API.

**Comment by NecroBones** [comment]
OK, I didn't see in the dumps how to get the orbital heirarchies. That is, which bodies orbit which stars, etc. Within a given system (with multiple stars).

**Comment by klightspeed** [comment]
System Synuefe AB-C d12, body Synuefe AB-C d12 A 1 a:
This is the first moon of the first planet of the first star in the system

System Synuefe BC-D d24, body Synuefe BC-D d24 2 c a:
This is the first moon of the third moon of the second planet orbiting the main star.

System Synuefe DE-F c23, body Synuefe DE-F c23 AB 2:
This is the second planet orbiting the A + B binary pair of stars

**Comment by NecroBones** [comment]
So parsing the names then. I was trying to avoid that, but OK. :)

**Comment by AnthorNet** [comment]
The offset in the dump and API are done from the names.

**Comment by NecroBones** [comment]
OK cool. The offset itself doesn't tell me who the parent is (by ID or whatever) so I'll just have to parse the names. Thanks,

**Comment by AnthorNet** [comment]
The parent is the previous body with offset -1, they are ordered like our front end with the exact same offset we use to move them to the right.

**Comment by NecroBones** [comment]
OK, I'll see if that will work, thanks. Previous in the API output? Parsing the names will still work too, which might be better since I'm working on a MySQL database that I built from the dumps. I'll probably have to write a script that parses these out and populates a column with parent object's ID so that I can just select against it later.

**Comment by klightspeed** [comment]
Any bodies scanned since 3.0 should also have a `bodyID` and a `parents` - the `bodyID` is the unique ID of the body within the system, and the `parents` is a list of `type: bodyID` pairs starting at the immediate parent and ending at the root node.

Note also that for some systems (mostly in the bubble), some bodies have had their name overridden (e.g. most if not all bodies in various lore systems).  For these systems, I have been gathering name to designation mappings in https://docs.google.com/spreadsheets/d/1kDtQYMeduzWghj1yXEsMY8isRccNhAr2XxYmaPIsB2o/edit#gid=711269421

**Comment by NecroBones** [comment]
Oh cool! I didn't realize those fields were added. Maybe I can start grabbing those going forward and then back-fill from parsing the names. It's OK if I mainly work with the proc-gen names and so forth, I just want as large of a sample size as I can reasonably use. 

EDIT: BTW, as an aside-- You can see some of the things I've been doing here: https://edastro.com/mapcharts/
