### ISSUE TITLE
EDSM Ships does not recognize Azure Paint Job.

### ISSUE THREAD

**Issue by incryptx** [EDSM-NET/FrontEnd#395]
I get a large orange box with a ? mark in it.

Ship Name: Krait MkII "Ka-Tana"
Paintjob: %%krait_mkii_lrpo_azure%%

Changed paintjob in Elite to Midnight Black, EDSM still does not see new paintjob.

**Comment by PhoenixRiver** [comment]
Similar issue to mine (#405):
For reference on this page: https://www.edsm.net/en/faq/ships/index/id/128816567/name/Krait+MkII both a screenshot for the default Krait MkII and the Midnight Black variant are shown but I found no reference to an Azure variant... is this still an issue since it might have taken EDSM a little time to update the screenshot reference when you tried the change to the Midnight Black variant... (I'm guessing as I've only just joined EDSM).

If you could provide a screenshot as specified here (fifth question down): https://www.edsm.net/en/faq it may be that the issue can be quickly fixed :)

**Comment by DanyDK** [comment]
Same issue for Asp Explorer Lakon White livery.
at the fleet page it writtenlike this:

Paintjob:
%%asp_largelogo_06%%

BTW there is no screenshot of this livery at https://www.edsm.net/en/faq/ships/index/id/128049303/name/Asp+Explorer

**Comment by AnthorNet** [comment]
Hello,

We will handle it there: EDSM-NET/Alias#12
