### ISSUE TITLE
Update process stopped at 20%

### ISSUE THREAD

**Issue by Kash0321** [EDSM-NET/FrontEnd#498]
Sorry to bother you again... I think it is not working on my account the data update process, it is stuck at 20% and the data collected is from a long time ago, 

It happens since switch from console to PC account was made (https://github.com/EDSM-NET/FrontEnd/issues/495)

![image](https://user-images.githubusercontent.com/10654401/229079040-36785900-2c25-4d92-bad4-33db37c49891.png)

![image](https://user-images.githubusercontent.com/10654401/229079154-7a52e432-299c-4bf2-8df8-422052fd679f.png)

Thanks a lot

**Comment by AnthorNet** [comment]
Hey, what software are you suing to sync with EDSM?

**Comment by Kash0321** [comment]
Hi Anthor.

I am not using any software, only web browser (MS Edge). The problem is that the data I can see in EDSM does not show the facts since my account change, from console (PS5) to PC. 

Sorry about my English, may be I'm not explaining myself too well.

**Comment by klightspeed** [comment]
The console updater is not supported when the account being synced from is not a console account.
In order to upload to EDSM, you will need to either upload your journals from `shell:savedgames\Frontier Developments\Elite Dangerous` on your computer to the [EDSM journal uploader](https://www.edsm.net/settings/import/journal), or use third-party software such as [EDMC](https://github.com/EDCD/EDMarketConnector), [EDDI](https://github.com/EDCD/EDDI), or [EDDiscovery](https://github.com/EDDiscovery/EDDiscovery) to do that for you (after having uploaded your old logs, as the former two applications do not support sending old journals to EDSM).  Alternatively, if you are using a cloud gaming service, you may be able to use a service such as [Journal Limpet](https://journal-limpet.com/) to retrieve your last 25 days' worth of logs.  In all these cases, after confirming that the account type is PC, you will need to grab the [EDSM API Key](https://www.edsm.net/settings/api) and put it into the commander / integration settings in whichever software or service you are using.

**Comment by Kash0321** [comment]
Understood, thank you all for the info.
